version: '3.8'
services:
  warthogs:
    build:
      context: .
      target: dev
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - POSTGRESQL_URL=jdbc:postgresql://db/warthogs
      - POSTGRESQL_USERNAME=warthogs
      - POSTGRESQL_PASSWORD=warthogs
    volumes:
      - ./:/app

  db:
    image: postgres:14.5-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=warthogs
      - POSTGRES_USER=warthogs
